### ISSUE TITLE
Font loading doesn't work for me

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#35] opened 2022-12-05 22:45 UTC
And in my port i don't get font loading to work. That is, my icons show up as question marks. I have tried adding
```
imgui_backends.opengl3_destroy_fonts_texture()
imgui_backends.opengl3_create_fonts_texture()
```
after the calls to `imgui.font_atlas_add_font_from_file_ttf` which i think should be needed because else the new font texture doesn't get built (not needed in your demo though, as you call these before the very first frame is rendered, and fonts are set up in `ImGui_ImplOpenGL3_CreateDeviceObjects()` which is called the first frame). So adding those calls didn't help. Guess i am doing something wrong as your demo does work. But what i have now worked with pyimgui, so i am wondering what the difference/my oversight is...

Also, when i try to use the ImFont returned from `imgui.font_atlas_add_font_from_file_ttf` with `imgui.push_font`, it asserts, probably because the font isn't loaded? I may be missing something here. Code is around here: https://github.com/dcnieho/glassesValidator/blob/imgui_bundle/src/glassesValidator/GUI/_impl/gui.py#L982

**Comment by pthom** [comment] 2022-12-07 07:40
Please inform me about the status when you have time. I will be happy to help :-)

**Comment by pthom** [comment] 2022-12-08 09:48
Well I made some test on my side with your code, since I wanted to be sure there is no issue on the library side.

You can find my tests in this zip:

[sandbox_fonts.zip](https://github.com/pthom/imgui_bundle/files/10184120/sandbox_fonts.zip)

Content:

````
sandbox_fonts/
├── IconsFontAwesome4.py
├── fonts/                                   # your fonts + fontawesome
│   ├── Karla-Regular.ttf
│   ├── NotoSans-Regular.ttf
│   ├── fontawesome-webfont.ttf
│   ├── materialdesignicons-webfont.7.0.96.ttf
│   └── materialdesignicons-webfont.ttf
├── icons_material_design.py
├── imgui.ini
└── sandbox_glassv_fonts.py  # my test
````

sandbox_glassv_fonts.py is just an adaptation of the bare imgui example where I copy-customized your code.


Results:

* I was able to reproduce your font loading error:
````python
            # MsgBox type icons
            # This line alone leads to IM_ASSERT( font && font->IsLoaded() )   ---   imgui.cpp:7795
            # self.icon_font = \
            #     imgui.font_atlas_add_font_from_file_ttf(imgui.get_io().fonts,str(mdi_path),   size_69,                       glyph_ranges_as_int_list=msgbox_range)

            # However, if you load before karla, then merge mdi, the error message disappears
            # it seems you cannot have a font without basic character set
            self.icon_font = \
                imgui.font_atlas_add_font_from_file_ttf(imgui.get_io().fonts,str(karla_path), size_69, glyph_ranges_as_int_list=karla_range)
            self.icon_font = \
                imgui.font_atlas_add_font_from_file_ttf(imgui.get_io().fonts,str(mdi_path), size_69, font_cfg=mdi_config, glyph_ranges_as_int_list=msgbox_range)
````

* the material design does not display icons on my side. I'd be interested in how you get it to display anything.

<img width="890" alt="image" src="https://user-images.githubusercontent.com/7694091/206414903-2e59058d-d321-45c1-b0eb-8e7f973ba469.png">

**Comment by dcnieho** [comment] 2022-12-08 21:24
Thank you VERY much for looking into this! I will hopefully be able to
study and run this tomorrow, else saturday. I will study it carefully.

Let me already reply: My ultimate aim is to move to hello_imgui, which
should be possible now that you have exposed glfw callback so i can put my
own. That should solve these problems if i understand you correctly?

The code as is worked with pyimgui, also with font reloading with an open
window due to dpi change. Perhaps pyimgui doesn't just cleanly wrap but has
some extra code in their for convenience. I do wonder why it no longer
loads.

For the material design font, icons are far in unicode space. With your
code things do work for me if i provide the right unicode code points in my
input strings, e.g. "󰌠 Python". Or i should say worked for me with
pyimgui, i also get question marks now...

**Comment by pthom** [comment] 2022-12-09 09:44
Good news!

I found the reason why the icons would not show. The answer was buried in imgui changelog:

CHANGELOG.txt: 
>  VERSION 1.76 (Released 2020-04-12)
> - Added optional support for Unicode plane 1-16 (#2538, #2541, #2815) [@cloudwu, @samhocevar]
>  - Compile-time enable with '#define IMGUI_USE_WCHAR32' in imconfig.h.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/7694091/206671837-049ac874-bf48-4205-a849-b52a6c2be160.png">


I was using the default version of ImWChar (16 bits), and your icons go beyond this range. This is now solved.

By the way I did some more changes:

 
f78e7a4 Correct fonts issues if far unicode planes: define IMGUI_USE_WCHAR32
Where I solve the issues with 32 bits glyphs.

ce50192 Add sandbox fonts
I added the font sandbox to the demos. 

04a6fe9 AddFontFromFileTTF patched for python inside imgui
ImFontAtlas.add_font_from_file_ttf() is now available under python (I patched imgui)
(and I **removed** the free function version)

01d51b8 ADAPT_IMGUI_BUNDLE: add SetIniFilename & SetLogFilename
ImGuio..set_ini_filename() replaces the free function version.

**Comment by dcnieho** [comment] 2022-12-09 12:24
Hi Pascal,

super you managed to figure this out! I was just looking through the
patches a bit (hopefully I can play with them properly tonight, just trying
to build a new pull of the dev branch now in the background. I like the
idea of doing the patches as you do, that keeps the interface clean and
simple for the users of your library. Will you do the same
for font_atlas_get_tex_data_as_rgba32?

More generally, I see that in litgen setup for imgui, you added
the RegexReplacementList. Do you think that can also be used to clean up
that dirty enum hack of imgui for some of the extensions in internal (like
what is now
 `imgui.internal.SelectableFlagsPrivate_.im_gui_selectable_flags_select_on_click`
and
should more ideally be
`imgui.internal.SelectableFlagsPrivate_.select_on_click`)?

I also noted that you are wrapping the materialdesign font so that glyphs
can be accessed by name instead of some arbitrary unicode codepoint. That
is super!

Cheers,
Dee

**Comment by pthom** [comment] 2022-12-09 13:10
Hi Dee,

> super you managed to figure this out! I was just looking through the
patches a bit (hopefully I can play with them properly tonight, just trying
to build a new pull of the dev branch now in the background

Keep me informed about the status once you have more info :-)

>  I like the idea of doing the patches as you do, that keeps the interface clean and simple for the users of your library.

Yes, it makes the python interface simpler. I think some people at ImGui will cringe when seeing `#include <vector>` in my patched imgui.h. May be I'll change to ImVector someday. 

> Will you do the same for font_atlas_get_tex_data_as_rgba32?
This one would require imgui to depend on pybind11/numpy, which is not a good idea. So, no.

> I also noted that you are wrapping the materialdesign font so that glyphs
can be accessed by name instead of some arbitrary unicode codepoint. That
is super!

_Beware_ that does not work at the moment for material design, only for font awesome. I guess the font and the python file are out of sync.

> More generally, I see that in litgen setup for imgui, you added
the RegexReplacementList. Do you think that can also be used to clean up
that dirty enum hack of imgui for some of the extensions in internal (like
what is now
 `imgui.internal.SelectableFlagsPrivate_.im_gui_selectable_flags_select_on_click`
and
should more ideally be
`imgui.internal.SelectableFlagsPrivate_.select_on_click`)?

I'll note it in another issue

**Comment by pthom** [comment] 2022-12-09 15:33
> More generally, I see that in litgen setup for imgui, you added
the RegexReplacementList. Do you think that can also be used to clean up
that dirty enum hack of imgui for some of the extensions in internal (like
what is now
imgui.internal.SelectableFlagsPrivate_.im_gui_selectable_flags_select_on_click
and
should more ideally be
imgui.internal.SelectableFlagsPrivate_.select_on_click)?

Fixed in #40

**Comment by dcnieho** [comment] 2022-12-10 00:49
This is super, font loading and the icons work for me as well now!

No need to change to ImVector, all's good!

Ok on the other points, i'm happy. I'll revisit the better way of
using material font icons once im making the next switch, over to
hello_imgui

**Comment by dcnieho** [comment] 2022-12-10 09:17
Regarding the material design font, this is the one i am using, not the one
from google itself: https://github.com/Templarian/MaterialDesign

**Comment by dcnieho** [comment] 2022-12-10 09:20
https://raw.githubusercontent.com/Templarian/MaterialDesign/master/meta.json
contains info about all codepoints in the font and associated names

**Comment by pthom** [comment] 2022-12-10 11:22
https://github.com/juliettef/IconFontCppHeaders could help you greatly

**Closed** 2022-12-10 21:42 UTC
Labels: user question
