### ISSUE TITLE
macos deployment target

### ISSUE THREAD

**Issue by dcnieho** [pthom/imgui_bundle#80] opened 2023-02-08 20:19 UTC
Despite your pyproject.toml listing 11.0 as a deployment target, the arm64 (but not the x86_64) wheels for 3.10 and 3.9 seem to have 13.0 as deployment target, see here: https://pypi.org/project/imgui-bundle/#files. That is causing trouble for some of my users who are on an M1, its a pretty high requirement to reach. Is it possible to correct that?

**Comment by dcnieho** [comment] 2023-02-09 07:27
Hmm, i have another M1 Mac user who (without xcode installed) had no problem a while ago. The WHEEL file in their imgui_bundle-0.8.2.dist-info lists this:

Wheel-Version: 1.0
Generator: skbuild 0.16.6
Root-Is-Purelib: false
Tag: cp310-cp310-macosx_10_16_x86_64

which surprises me. Apparently they run through rosetta:
sysconfig.get_platform()
'macosx-10.9-x86_64'
sysconfig.get_config_vars()['HOST_GNU_TYPE']
'x86_64-apple-darwin13.4.0'

Thats fine, but what surprises me is that they have a macosx_10_16 wheel while whats on pypi for 0.8.2 is a macosx_11_0 wheel.

Whats the lowest deployment target you can get away with by the way? The lower the better is my understand, because the more compatible.

**Comment by dcnieho** [comment] 2023-02-09 13:32
The other user now managed to install after installing xcode (compile failed since they didn't have it, xcrun not found). This is whats in the wheel file of the installed package:
Wheel-Version: 1.0
Generator: skbuild 0.16.6
Root-Is-Purelib: false
Tag: cp310-cp310-macosx_10_16_x86_64

sysconfig.get_platform()
'macosx-10.9-x86_64'
sysconfig.get_config_vars()['HOST_GNU_TYPE']
'x86_64-apple-darwin13.4.0'

So same as the other guy for which it did work

**Comment by pthom** [comment] 2023-02-09 23:44
I'm sorry I'm on holiday, and do not have much time for this.
Some details: the mac wheels are built by cibuildwheel.

For x86_64, they are built on github. For ARM, I cannot trust github builders since they are running on Intel Mac and a dependency on Intel IPP is added even if they are trying to build for ARM.

So I have to build them on my own mac. I build them with cibuildwheel also, and I just replace `archs = ["arm64"]` inside pyproject.toml

So the build should be targeting 11.0, since pyproject mentions: 
MACOSX_DEPLOYMENT_TARGET="11.0"

And this is what I see during the build:
<img width="229" alt="image" src="https://user-images.githubusercontent.com/7694091/217963730-39807ffd-f055-4a2e-848d-b83ebe7c9776.png">


However, near the end, I can read an unhelpful message in the build log:

```
  [WARNING] This wheel needs a higher macOS version than is set in MACOSX_DEPLOYMENT_TARGET variable.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 13_0 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:
  _skbuild/macosx-11.0-arm64-3.9/setuptools/bdist.macosx-11.0-arm64/wheel/imgui_bundle/_imgui_bundle.cpython-311-darwin.so[WARNING] This wheel needs a higher macOS version than is set in MACOSX_DEPLOYMENT_TARGET variable.  To silence this warning, set MACOSX_DEPLOYMENT_TARGET to at least 13_0 or recreate these files with lower MACOSX_DEPLOYMENT_TARGET:
  _skbuild/macosx-11.0-arm64-3.9/setuptools/bdist.macosx-11.0-arm64/wheel/imgui_bundle/_imgui_bundle.cpython-311-darwin.socreating _skbuild/macosx-11.0-arm64-3.9/setuptools/bdist.macosx-11.0-arm64/wheel/imgui_bundle-0.8.3.dist-info/WHEEL
  creating '/private/var/folders/w1/w77kvvl9613022ksfxj7v8xh0000gn/T/pip-wheel-2w3mmnbn/.tmp-p0oakfmp/imgui_bundle-0.8.3-cp39-cp39-macosx_13_0_arm64.whl' and adding '_skbuild/macosx-11.0-arm64-3.9/setuptools/bdist.macosx-11.0-arm64/wheel' to it

```


Attached are the full logs:


[cib_err.txt](https://github.com/pthom/imgui_bundle/files/10702462/cib_err.txt)
[cib_log.txt](https://github.com/pthom/imgui_bundle/files/10702463/cib_log.txt)

**Comment by dcnieho** [comment] 2023-02-13 08:03
Enjoy your holiday! No rush!

I do see `-DCMAKE_OSX_DEPLOYMENT_TARGET=11.0` in the command lines, i am not sure what that acts on though.

Maybe its the OpenCV? Have you tried specifying `-mmacosx-version-min=11` for the compiler command lines? How have you chosen 11.0 by the way? The lower the better I think, as long as the compiler toolchain still supports what you need. It seems 10.9 is common, for my own project i had to use 10.14 due to need for c++17 features (if i recall correctly, thats the first version where those are properly supported).

**Comment by pthom** [comment] 2023-11-01 07:12
Closing this, as I cannot reproduce it, and it was probably solved in the next releases. Please reopen if still present.

**Closed by pthom** 2023-11-01 07:12 UTC

**Comment by dcnieho** [comment] 2024-06-06 13:45
So that's the following locations where you could set 10.14 instead of 11.0:
https://github.com/pthom/imgui_bundle/blob/670c72e0cab1beaa4a5761861286dd3f871b4ead/pyproject.toml#L83
https://github.com/pthom/imgui_bundle/blob/670c72e0cab1beaa4a5761861286dd3f871b4ead/.github/workflows/pip.yml#L9
https://github.com/pthom/imgui_bundle/blob/670c72e0cab1beaa4a5761861286dd3f871b4ead/.github/workflows/cpp_lib.yml#L10
https://github.com/pthom/imgui_bundle/blob/670c72e0cab1beaa4a5761861286dd3f871b4ead/.github/workflows/cpp_lib_with_bindings.yml#L10
